# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'p2hacks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for p2hacks
   # Pods for testing
 pod 'Firebase'
 pod 'Firebase/Core' 
 pod 'Firebase/Database' 
  target 'p2hacksTests' do
  end

  inherit! :search_paths
    # Pods for testing
  end

  target 'p2hacksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

